### ISSUE TITLE
build fails on Windows

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-files#18]
The build fails on Windows, mostly due to platform specifics in the code. Let's fix this.

**Comment by yegor256** [comment]
@Graur please, help

**Comment by Graur** [comment]
@yegor256 I think we need to come up with a method for handling the file separator. Right now we can pass string to `base-name` with the `/` line separator, but it will fail on Windows. Maybe it would be better to build file path?
e.g.
```
base-name
.with "tmp"
.with "foo"
.with "bar.txt"
```

**Comment by Graur** [comment]
@yegor256 What should we do with such kind of tests?
```
[] > takes-name-of-directory
  eq. > @
    dir-name
      "/tmp/foo/hello.gz"
    "/tmp/foo"
```
Here we can see the example on Mac and Ubuntu test, which is passed. But on Windows will pass only this one:
```
[] > takes-name-of-directory
  eq. > @
    dir-name
      "/tmp/foo/hello.gz"
    "\\tmp\\foo"
```

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#36](https://github.com/objectionary/eo-files/issues/36) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#36](https://github.com/objectionary/eo-files/issues/36) is solved here.
