### ISSUE TITLE
Incorrect example in README.md

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo-files#67]
**First example in `README.md` is incorrect:**
```
each. > @
  select.
    QQ.fs.walk.
      QQ.fs.dir "/tmp"
      "**/*"
    [f]
      and. > @
        f.is-dir.not
        matches.
          QQ.txt.regex
            "\.txt$"
          f
  [f]
    QQ.io.stdout > @
      QQ.txt.sprintf "file: %s" f
```
`walk` is an attribute of `QQ.fs.dir`, so `walk.` is need to be specified instead of `QQ.fs.walk.`.
String `"\.txt$"` is not parsed with such error:
![image](https://user-images.githubusercontent.com/70313618/214606362-c12860f6-395b-4838-9e4f-8944b6d7b127.png)
So, maybe it need to be replaced by `".*\\.txt$"` (as I understood from the context)

**Сorrected example looks like this:**
```
each. > @
  select.
    walk.
      QQ.fs.dir "/tmp"
      "**/*"
    [f]
      and. > @
        f.is-dir.not
        matches.
          QQ.txt.regex
            ".*\\.txt$"
          f
  [f]
    QQ.io.stdout > @
      QQ.txt.sprintf "file: %s" f
```
Even so it just compiles but doesn't runs. The output is:
![image](https://user-images.githubusercontent.com/70313618/214608196-b4c24ba2-9a4d-43ef-9ec7-875b9427d17e.png)
`array` doesn't have `select` attribute, and I can't figure out where this attribute is located.

**Comment by c71n93** [comment]
@mximp can you have a look, please?

**Comment by yegor256** [comment]
@c71n93 send us a pull request please
