### ISSUE TITLE
dir.walk that doesn't expect an array

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-files#8]
It seems, that it would be better to make `dir.walk` accept a single term as condition to filter directories. 
So the argument of `walk` has to be a decorator of `bool`.

**Comment by yegor256** [comment]
@maxonfjvipon very good point. want to submit a PR?

**Comment by maxonfjvipon** [comment]
@yegor256 there are some misunderstandings. In calculus paper I saw that `walk` accepts 1 parameter which is an array with 1 abstract object with 1 free attribute.

<img width="149" alt="image" src="https://user-images.githubusercontent.com/37025995/169666923-5971b0f5-bba4-4fbb-902b-4941f436313d.png">

From tests and code in repo I see that `walk` accepts string which is used as filter for files walking "walking".

<img width="529" alt="image" src="https://user-images.githubusercontent.com/37025995/169666977-251f7d6f-5de2-4dd9-b819-b51aca89106d.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/37025995/169667012-94ec6373-6479-408d-baba-e8792c5ff6cd.png">

So could you please clarify the situation and do we really need a `bool` object as a parameter of `walk` for filtering?

**Comment by yegor256** [comment]
@maxonfjvipon yes, this is how it should work:

```
(dir "./tmp").walk
   [f]
     or. > @
       f.is-dir
       f.name.matches "*.txt" # whatever
```

let's fix both the code and the paper.

**Comment by yegor256** [comment]
@maxonfjvipon the right way is the way it's implemented now. The filtering is outside of scope of this lib. We just do `walk` and return an array as file system suggests to us. Then, the array is filtered as a normal array.

**Comment by maxonfjvipon** [comment]
@yegor256 As you wish. But if we talk about this feature - filter directories by condition - where should it be and should it?  
P.S. we still need to fix the paper
