### ISSUE TITLE
Update dependency org.eolang:eo-runtime to v0.32.0

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-files#89]
#85 fails, we need to do it manually

**Comment by levBagryansky** [comment]
@maxonfjvipon Couild you please assign me

**Comment by 0pdd** [comment]
@levBagryansky 3 puzzles [#95](https://github.com/objectionary/eo-files/issues/95), [#96](https://github.com/objectionary/eo-files/issues/96), [#97](https://github.com/objectionary/eo-files/issues/97) are still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by levBagryansky** [comment]
@yegor256 can we release it in order to update home? to 0.4.1

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.1`
